# Generated by Django 5.1.7 on 2025-04-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateField(default='YYYY-MM-DD', verbose_name='Дата публикации'),
        ),
    ]
